functions:
- refSiblings
rules:
  schema-has-examples:
    description: Schemas should not have examples. Use property example values instead.
    severity: info
    given: $..examples
    then:
      function: falsy
  schema-has-ref-sibling:
    description: Properties must not be placed alongside a `$ref`.
    resolved: false
    severity: info
    given: $..[?(@property === '$ref')]
    then:
      function: refSiblings
  schema-has-x-external:
    description: Don't define `x-external` at the top level.
    severity: info
    given: $["x-external"]
    then:
    - function: undefined
  schema-has-x-internal:
    description: Don't define `x-internal` at the top level.
    severity: info
    given: $["x-internal"]
    then:
    - function: undefined