---
description: "Rules related to generic schemas."
---
functions:
  - refSiblings
rules:
  schema-has-examples:
    description: Schemas should not have examples. Use property example values instead.
    incorrect: |-      
      {
        "parameters": [
          {
            "name": "limit",
            "in": "query",
            "examples": {
              "zero": {
                "value": 0,
                "summary": "When the limit is 0"
              }
            }
          }
        ]
      }
    incorrect-prism-highlight: "6-11"
    correct: |-
      {
        "parameters": [
          {
            "name": "limit",
            "in": "query",
            "schema": {
              "type": "number",
              "example": 0
            }            
          }
        ]
      }      
    correct-prism-highlight: "6-9"
    severity: off
    given: '$..examples'
    then:
      function: falsy
  schema-has-ref-sibling:
    description: Properties must not be placed alongside a `$ref`.
    incorrect: |-
      {
        "portfolio": {
          "$ref": "./CompanyPortfolio.json",
          "description": "A company portfolio object."
        }
      }
    incorrect-prism-highlight: "4"
    correct: |-
      {
        "portfolio": {
          "$ref": "./CompanyPortfolio.json"
        }
      }
    correct-prism-highlight: ""
    resolved: false
    severity: off
    given: "$..[?(@property === '$ref')]"
    then:
      function: refSiblings
  schema-has-x-external:
    description: Don't define `x-external` at the top level.
    incorrect: |-
      {
        "title": "ResponseObject",
        "x-external": false
      }
    incorrect-prism-highlight: "3"
    correct: |-
      {
        "title": "ResponseObject"
      }
    correct-prism-highlight: ""
    severity: off
    given: '$["x-external"]'
    then:
      - function: undefined
  schema-has-x-internal:
    description: Don't define `x-internal` at the top level.
    incorrect: |- 
      {
        "title": "ResponseObject",
        "x-internal": true
      }
    incorrect-prism-highlight: "3"
    correct: |-
      {
        "title": "ResponseObject"
      }
    correct-prism-highlight: ""
    severity: off
    given: '$["x-internal"]'
    then:
      - function: undefined